package com.alibaba.intl.bcds.goldroom.dataobject;

import java.util.Date;

public class MemberLog {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEMBER_LOG.ID
     *
     * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEMBER_LOG.GMT_CREATE
     *
     * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
     */
    private Date gmtCreate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEMBER_LOG.GMT_MODIFIED
     *
     * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
     */
    private Date gmtModified;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEMBER_LOG.LOG_TYPE
     *
     * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
     */
    private Integer logType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEMBER_LOG.LOG_MSG
     *
     * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
     */
    private String logMsg;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEMBER_LOG.MEMBER_ID
     *
     * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
     */
    private Integer memberId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEMBER_LOG.ID
     *
     * @return the value of MEMBER_LOG.ID
     *
     * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEMBER_LOG.ID
     *
     * @param id the value for MEMBER_LOG.ID
     *
     * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEMBER_LOG.GMT_CREATE
     *
     * @return the value of MEMBER_LOG.GMT_CREATE
     *
     * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEMBER_LOG.GMT_CREATE
     *
     * @param gmtCreate the value for MEMBER_LOG.GMT_CREATE
     *
     * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEMBER_LOG.GMT_MODIFIED
     *
     * @return the value of MEMBER_LOG.GMT_MODIFIED
     *
     * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEMBER_LOG.GMT_MODIFIED
     *
     * @param gmtModified the value for MEMBER_LOG.GMT_MODIFIED
     *
     * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEMBER_LOG.LOG_TYPE
     *
     * @return the value of MEMBER_LOG.LOG_TYPE
     *
     * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
     */
    public Integer getLogType() {
        return logType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEMBER_LOG.LOG_TYPE
     *
     * @param logType the value for MEMBER_LOG.LOG_TYPE
     *
     * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
     */
    public void setLogType(Integer logType) {
        this.logType = logType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEMBER_LOG.LOG_MSG
     *
     * @return the value of MEMBER_LOG.LOG_MSG
     *
     * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
     */
    public String getLogMsg() {
        return logMsg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEMBER_LOG.LOG_MSG
     *
     * @param logMsg the value for MEMBER_LOG.LOG_MSG
     *
     * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
     */
    public void setLogMsg(String logMsg) {
        this.logMsg = logMsg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEMBER_LOG.MEMBER_ID
     *
     * @return the value of MEMBER_LOG.MEMBER_ID
     *
     * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEMBER_LOG.MEMBER_ID
     *
     * @param memberId the value for MEMBER_LOG.MEMBER_ID
     *
     * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }
}