CREATE TABLE BOOK_INFO (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  AUTHOR VARCHAR(100) NULL,
  NAME VARCHAR(100) NULL,
  PUBLISHER VARCHAR(100) NULL,
  PUBLISH_TIME DATE NULL,
  ISBN VARCHAR(50) NOT NULL,
  CATEGORY_NAME VARCHAR(50) NOT NULL,
  CATEGORY_ID INTEGER UNSIGNED NULL,
  IMG_URL VARCHAR(1000) NULL,
  DESCRIPTION VARCHAR(5000) NULL,
  GMT_CREATE DATETIME NULL,
  GMT_MODIFIED DATETIME NULL,
  EDITION VARCHAR(100) NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE BOOK_ITEM (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  STATE INTEGER UNSIGNED NULL,
  OWNER_ID INTEGER UNSIGNED NULL,
  ADD_TIME DATETIME NOT NULL,
  REMOVE_TIME DATETIME NULL,
  BOOK_INFO_ID INTEGER UNSIGNED NULL,
  FIRST_ADD_TIME DATETIME NULL,
  GMT_CREATE DATETIME NULL,
  GMT_MODIFIED DATETIME NULL,
  TAGS VARCHAR(500) NULL,
  PRIMARY KEY(ID)
);

ALTER   TABLE   BOOK_ITEM   CHANGE   STATE   STATE   varchar(50)   NOT   NULL

CREATE TABLE BOOK_ITEM_LOG (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  GMT_CREATE DATETIME NULL,
  GMT_MODIFIED DATETIME NULL,
  LOG_TYPE INTEGER UNSIGNED NULL,
  LOG_MSG VARCHAR(500) NULL,
  BOOK_ITEM_ID INTEGER UNSIGNED NULL,
  PRIMARY KEY(ID)
)
TYPE=InnoDB;

CREATE TABLE CATEGORY (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  PARENT_ID INTEGER UNSIGNED NULL,
  NAME VARCHAR(50) NULL,
  DESCRIPTION VARCHAR(1000) NULL,
  GMT_CREATE DATETIME NULL,
  GMT_MODIFIED DATETIME NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE LENDING (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  OWNER_ID INTEGER UNSIGNED NOT NULL,
  SUBSCRIBER_ID INTEGER UNSIGNED NOT NULL,
  LENDING_TIME DATETIME NULL,
  RETURN_TIME DATETIME NULL,
  STATE INTEGER UNSIGNED NULL,
  BOOK_ITEM_ID INTEGER UNSIGNED NULL,
  REAL_RETURN_TIME DATETIME NULL,
  GMT_CREATE DATETIME NULL,
  GMT_MODIFIED DATETIME NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE LENDING_LOG (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  SUBSCRIBER_ID INTEGER UNSIGNED NULL,
  BOOK_ITEM_ID INTEGER UNSIGNED NULL,
  BOOK_INFO_ID INTEGER UNSIGNED NULL,
  LOG_TYPE INTEGER UNSIGNED NULL,
  LOG_MSG VARCHAR(500) NULL,
  GMT_CREATE DATETIME NULL,
  GMT_MODIFIED DATETIME NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE MEMBER (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(20) NULL,
  WORK_ID INTEGER UNSIGNED NULL,
  LOGIN_ID VARCHAR(50) NULL,
  PASSWORD VARCHAR(50) NULL,
  EMAIL VARCHAR(50) NULL,
  ALI_TALK_ID VARCHAR(50) NULL,
  GMT_CREATE DATETIME NULL,
  GMT_MODIFIED DATETIME NULL,
  ENABLE INTEGER UNSIGNED NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE MEMBER_LOG (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  GMT_CREATE DATETIME NULL,
  GMT_MODIFIED DATETIME NULL,
  LOG_TYPE INTEGER UNSIGNED NULL,
  LOG_MSG VARCHAR(500) NULL,
  MEMBER_ID INTEGER UNSIGNED NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE RESERVATION (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  OWNER_ID INTEGER UNSIGNED NULL,
  SUBSCRIBER_ID INTEGER UNSIGNED NULL,
  LEND_BOOK_TIME DATETIME NULL,
  RETURN_TIME DATETIME NULL,
  STATE INTEGER UNSIGNED NULL,
  BOOK_ITEM_ID INTEGER UNSIGNED NULL,
  GMT_CREATE DATETIME NULL,
  GMT_MODIFIED DATETIME NULL,
  PRIMARY KEY(ID)
);


create table member_role(
    ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
   member_id INTEGER UNSIGNED NOT NULL,
   role_id INTEGER UNSIGNED NOT NULL,
PRIMARY KEY(ID)
);

create table role(
    ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  name  VARCHAR(50),
   description VARCHAR(50),
PRIMARY KEY(ID)
);


