package com.alibaba.intl.bcds.goldroom.dao;

import java.sql.SQLException;

import com.alibaba.intl.bcds.goldroom.dataobject.MemberLog;

public interface MemberLogDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table MEMBER_LOG
     * 
     * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
     */
    int deleteByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table MEMBER_LOG
     * 
     * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
     */
    void insert(MemberLog record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table MEMBER_LOG
     * 
     * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
     */
    void insertSelective(MemberLog record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table MEMBER_LOG
     * 
     * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
     */
    MemberLog selectByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table MEMBER_LOG
     * 
     * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
     */
    int updateByPrimaryKeySelective(MemberLog record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table MEMBER_LOG
     * 
     * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
     */
    int updateByPrimaryKey(MemberLog record) throws SQLException;
}
