CREATE TABLE BOOK_INFO (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  AUTHOR VARCHAR(100) NULL,
  NAME VARCHAR(100) NULL,
  PUBLISHER VARCHAR(100) NULL,
  PUBLISH_TIME DATE NULL,
  ISBN VARCHAR(50) NOT NULL,
  CATEGORY_ID INTEGER UNSIGNED NULL,
  IMG_URL VARCHAR(1000) NULL,
  DESCRIPTION VARCHAR(5000) NULL,
  GMT_CREATE DATETIME NULL,
  GMT_MODIFIED DATETIME NULL,
  EDITION VARCHAR(100) NULL,
  PRIMARY KEY(ID)
);
ALTER TABLE BOOK_INFO ADD COLUMN `PAGES` INT(10) UNSIGNED AFTER `EDITION`,
 ADD COLUMN `TRANSLATOR` VARCHAR(100) AFTER `PAGES`,
 ADD COLUMN `CATEGORY_NAME` VARCHAR(50) AFTER `TRANSLATOR`,
 ADD COLUMN `SOURCE` VARCHAR(50) AFTER `CATEGORY_NAME`,
 ADD COLUMN `ISBN_10` VARCHAR(50) AFTER `SOURCE`,
 ADD COLUMN `ISBN_13` VARCHAR(50) AFTER `ISBN_10`;

CREATE TABLE BOOK_ITEM (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  STATE VARCHAR(50)  NULL,
  LOGIN_ID VARCHAR(50) NULL,
  ADD_TIME DATETIME NOT NULL,
  REMOVE_TIME DATETIME NULL,
  BOOK_INFO_ID INTEGER UNSIGNED NULL,
  FIRST_ADD_TIME DATETIME NULL,
  GMT_CREATE DATETIME NULL,
  GMT_MODIFIED DATETIME NULL,
  TAGS VARCHAR(500) NULL,
  PRIMARY KEY(ID)
);
ALTER TABLE BOOK_ITEM ADD COLUMN `REMARK` VARCHAR(500) NOT NULL AFTER `TAGS`;


CREATE TABLE BOOK_ITEM_LOG (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  GMT_CREATE DATETIME NULL,
  GMT_MODIFIED DATETIME NULL,
  LOG_TYPE INTEGER UNSIGNED NULL,
  LOG_MSG VARCHAR(500) NULL,
  BOOK_ITEM_ID INTEGER UNSIGNED NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE CATEGORY (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  PARENT_ID INTEGER UNSIGNED NULL,
  NAME VARCHAR(50) NULL,
  IS_LEAF INTEGER,
  LEVEL INTEGER,
  DESCRIPTION VARCHAR(1000) NULL,
  GMT_CREATE DATETIME NULL,
  GMT_MODIFIED DATETIME NULL,
  PRIMARY KEY(ID)
);


CREATE TABLE LENDING (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  SUBSCRIBER VARCHAR(50)  NOT NULL,
  LEND_TIME DATETIME NULL,
  RETURN_TIME DATETIME NULL,
  STATE VARCHAR(50) NULL,
  BOOK_ITEM_ID INTEGER UNSIGNED NULL,
  REAL_RETURN_TIME DATETIME NULL,
  GMT_CREATE DATETIME NULL,
  GMT_MODIFIED DATETIME NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE LENDING_LOG (
  ID INTEGER UNSIGNED NOT NULL ,
  SUBSCRIBER VARCHAR(50)  NOT NULL,
  LENDING_TIME DATETIME NULL,
  RETURN_TIME DATETIME NULL,
  STATE VARCHAR(50) NULL,
  BOOK_ITEM_ID INTEGER UNSIGNED NULL,
  REAL_RETURN_TIME DATETIME NULL,
  GMT_CREATE DATETIME NULL,
  GMT_MODIFIED DATETIME NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE MEMBER (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(20) NULL,
  WORK_ID INTEGER UNSIGNED NULL,
  LOGIN_ID VARCHAR(50) NULL,
  PASSWORD VARCHAR(50) NULL,
  EMAIL VARCHAR(50) NULL,
  ALI_TALK_ID VARCHAR(50) NULL,
  GMT_CREATE DATETIME NULL,
  GMT_MODIFIED DATETIME NULL,
  ENABLE INTEGER UNSIGNED NULL,
  ROLE VARCHAR(45) NULL,
  PRIMARY KEY(ID)
);
ALTER TABLE MEMBER ADD COLUMN `LOCATION` VARCHAR(100) AFTER `ENABLE`, ADD COLUMN `EXT` VARCHAR(45) AFTER `LOCATION`;

CREATE TABLE MEMBER_LOG (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  GMT_CREATE DATETIME NULL,
  GMT_MODIFIED DATETIME NULL,
  LOG_TYPE INTEGER UNSIGNED NULL,
  LOG_MSG VARCHAR(500) NULL,
  MEMBER_ID INTEGER UNSIGNED NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE RESERVATION (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  SUBSCRIBER VARCHAR(50)  NULL,
  LEND_TIME DATETIME NULL,
  RETURN_TIME DATETIME NULL,
  STATE VARCHAR(50)  NULL,
  BOOK_ITEM_ID INTEGER UNSIGNED NULL,
  GMT_CREATE DATETIME NULL,
  GMT_MODIFIED DATETIME NULL,
  PRIMARY KEY(ID)
);




CREATE TABLE INTEGRAL (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  GMT_CREATE DATETIME NULL,
  GMT_MODIFIED DATETIME NULL,
  LOGIN_ID VARCHAR(50) NULL,
  VALUE BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY(ID)
);
