package com.alibaba.intl.bcds.goldroom.dataobject;

public class Role {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column role.ID
     *
     * @ibatorgenerated Tue Nov 03 10:56:17 CST 2009
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column role.name
     *
     * @ibatorgenerated Tue Nov 03 10:56:17 CST 2009
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column role.description
     *
     * @ibatorgenerated Tue Nov 03 10:56:17 CST 2009
     */
    private String description;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column role.ID
     *
     * @return the value of role.ID
     *
     * @ibatorgenerated Tue Nov 03 10:56:17 CST 2009
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column role.ID
     *
     * @param id the value for role.ID
     *
     * @ibatorgenerated Tue Nov 03 10:56:17 CST 2009
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column role.name
     *
     * @return the value of role.name
     *
     * @ibatorgenerated Tue Nov 03 10:56:17 CST 2009
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column role.name
     *
     * @param name the value for role.name
     *
     * @ibatorgenerated Tue Nov 03 10:56:17 CST 2009
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column role.description
     *
     * @return the value of role.description
     *
     * @ibatorgenerated Tue Nov 03 10:56:17 CST 2009
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column role.description
     *
     * @param description the value for role.description
     *
     * @ibatorgenerated Tue Nov 03 10:56:17 CST 2009
     */
    public void setDescription(String description) {
        this.description = description;
    }
}