package com.alibaba.intl.bcds.goldroom.dao;

import java.sql.SQLException;
import java.util.List;

import com.alibaba.intl.bcds.goldroom.dataobject.Member;

public interface MemberDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table MEMBER
	 * 
	 * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
	 */
	int deleteByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table MEMBER
	 * 
	 * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
	 */
	void insert(Member record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table MEMBER
	 * 
	 * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
	 */
	void insertSelective(Member record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table MEMBER
	 * 
	 * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
	 */
	Member selectByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table MEMBER
	 * 
	 * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
	 */
	int updateByPrimaryKeySelective(Member record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table MEMBER
	 * 
	 * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
	 */
	int updateByPrimaryKey(Member record) throws SQLException;

	List<Member> listMemberByLoginIds(List loginIds) throws SQLException;
}