package com.alibaba.intl.bcds.goldroom.dao;

import java.sql.SQLException;

import com.alibaba.intl.bcds.goldroom.dataobject.Reservation;

public interface ReservationDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table RESERVATION
     * 
     * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
     */
    int deleteByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table RESERVATION
     * 
     * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
     */
    void insert(Reservation record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table RESERVATION
     * 
     * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
     */
    void insertSelective(Reservation record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table RESERVATION
     * 
     * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
     */
    Reservation selectByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table RESERVATION
     * 
     * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
     */
    int updateByPrimaryKeySelective(Reservation record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table RESERVATION
     * 
     * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
     */
    int updateByPrimaryKey(Reservation record) throws SQLException;
}
