package com.alibaba.intl.bcds.goldroom.dataobject;

import java.util.Date;

public class Member {
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column MEMBER.ID
	 * 
	 * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
	 */
	private Integer id;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column MEMBER.NAME
	 * 
	 * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
	 */
	private String name;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column MEMBER.WORK_ID
	 * 
	 * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
	 */
	private Integer workId;	

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column MEMBER.LOGIN_ID
	 * 
	 * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
	 */
	private String loginId;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column MEMBER.PASSWORD
	 * 
	 * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
	 */
	private String password;	

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column MEMBER.EMAIL
	 * 
	 * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
	 */
	private String email;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column MEMBER.ALI_TALK_ID
	 * 
	 * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
	 */
	private String aliTalkId;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column MEMBER.GMT_CREATE
	 * 
	 * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
	 */
	private Date gmtCreate;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column MEMBER.GMT_MODIFIED
	 * 
	 * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
	 */
	private Date gmtModified;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column MEMBER.ENABLE
	 * 
	 * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
	 */
	private Integer enable;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column MEMBER.ID
	 * 
	 * @return the value of MEMBER.ID
	 * 
	 * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column MEMBER.ID
	 * 
	 * @param id
	 *            the value for MEMBER.ID
	 * 
	 * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column MEMBER.NAME
	 * 
	 * @return the value of MEMBER.NAME
	 * 
	 * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column MEMBER.NAME
	 * 
	 * @param name
	 *            the value for MEMBER.NAME
	 * 
	 * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column MEMBER.WORK_ID
	 * 
	 * @return the value of MEMBER.WORK_ID
	 * 
	 * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
	 */
	public Integer getWorkId() {
		return workId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column MEMBER.WORK_ID
	 * 
	 * @param workId
	 *            the value for MEMBER.WORK_ID
	 * 
	 * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
	 */
	public void setWorkId(Integer workId) {
		this.workId = workId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column MEMBER.LOGIN_ID
	 * 
	 * @return the value of MEMBER.LOGIN_ID
	 * 
	 * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
	 */
	public String getLoginId() {
		return loginId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column MEMBER.LOGIN_ID
	 * 
	 * @param loginId
	 *            the value for MEMBER.LOGIN_ID
	 * 
	 * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
	 */
	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column MEMBER.PASSWORD
	 * 
	 * @return the value of MEMBER.PASSWORD
	 * 
	 * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column MEMBER.PASSWORD
	 * 
	 * @param password
	 *            the value for MEMBER.PASSWORD
	 * 
	 * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column MEMBER.EMAIL
	 * 
	 * @return the value of MEMBER.EMAIL
	 * 
	 * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column MEMBER.EMAIL
	 * 
	 * @param email
	 *            the value for MEMBER.EMAIL
	 * 
	 * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column MEMBER.ALI_TALK_ID
	 * 
	 * @return the value of MEMBER.ALI_TALK_ID
	 * 
	 * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
	 */
	public String getAliTalkId() {
		return aliTalkId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column MEMBER.ALI_TALK_ID
	 * 
	 * @param aliTalkId
	 *            the value for MEMBER.ALI_TALK_ID
	 * 
	 * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
	 */
	public void setAliTalkId(String aliTalkId) {
		this.aliTalkId = aliTalkId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column MEMBER.GMT_CREATE
	 * 
	 * @return the value of MEMBER.GMT_CREATE
	 * 
	 * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
	 */
	public Date getGmtCreate() {
		return gmtCreate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column MEMBER.GMT_CREATE
	 * 
	 * @param gmtCreate
	 *            the value for MEMBER.GMT_CREATE
	 * 
	 * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
	 */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column MEMBER.GMT_MODIFIED
	 * 
	 * @return the value of MEMBER.GMT_MODIFIED
	 * 
	 * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
	 */
	public Date getGmtModified() {
		return gmtModified;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column MEMBER.GMT_MODIFIED
	 * 
	 * @param gmtModified
	 *            the value for MEMBER.GMT_MODIFIED
	 * 
	 * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
	 */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column MEMBER.ENABLE
	 * 
	 * @return the value of MEMBER.ENABLE
	 * 
	 * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
	 */
	public Integer getEnable() {
		return enable;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column MEMBER.ENABLE
	 * 
	 * @param enable
	 *            the value for MEMBER.ENABLE
	 * 
	 * @ibatorgenerated Tue Sep 29 19:05:09 CST 2009
	 */
	public void setEnable(Integer enable) {
		this.enable = enable;
	}
}